# render.yaml

services:
  - type: web
    name: react-app
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    env:
      - name: REACT_APP_API_URL
        fromService:
          name: api
          port: 3001
  - type: web
    name: api
    buildCommand: npm run build-api
    startCommand: npm run start-api
    healthCheckPath: /health

routes:
  - type: rewrite
    source: /
    destination: /index.html

environments:
  - name: production
    secrets:
      - name: REACT_APP_API_URL
        fromService:
          name: api
          port: 3001
